environment:

  matrix:

  - PYTHON: "C:\\Python36-x64"

install:
- "set PATH=%PYTHON%\\Scripts;%PATH%"
- "%PYTHON%\\python.exe -m pip install --upgrade pip"
- "pip install --upgrade pip setuptools wheel"
- "pip install ."

build: false

test_script:
- "%PYTHON%\\python.exe -m unittest"
